### ISSUE TITLE
Where do I find the widget id?

### ISSUE THREAD

**Issue by sethshoultes** [PragmaticWebLimited/chatlio-for-wordpress#2]
Am I supposed to enter a random string for this?

**Comment by sethshoultes** [comment]
I tried entering a random string, but I am not seeing anything in the WordPress widgets page for Chatlio, nor am I seeing a working example on your website: http://chatlio.pragmatic-web.co.uk/

**Comment by pragmatic-web** [comment]
Thanks @sethshoultes - will look into the demo not working but it's on our main site: https://www.pragmatic-web.co.uk/

Widget ID you get from your Chatlio account page. Are you all set up there? If you're logged in, click here: https://chatlio.com/app/#/setup to grab the widget ID from this line:

`n.setAttribute("data-widget-id","f8cc9f2e-9375-41df-5cbc-dee1e2526dc5");`

**Comment by sethshoultes** [comment]
Got it. Thanks!
