### ISSUE TITLE
Cloudflare's rocketscript breaks things

### ISSUE THREAD

**Issue by pragmatic-web** [PragmaticWebLimited/chatlio-for-wordpress#4]
> Missing widget UUID. Did you set the 'data-widget-id' attribute?
> w.chatlio-widget.js:1 Uncaught TypeError: Cannot read property 'forceRequireLoad' of undefined
> w.chatlio-widget.js:1 Missing widget UUID. Did you set the 'data-widget-id' attribute?
> w.chatlio-widget.js:1 Uncaught TypeError: Cannot read property 'forceRequireLoad' of undefined

Initial report from @jeberly suggests Cloudflare might be the issue, along with a proposed fix.

**Comment by ghost** [comment]
@pragmatic-web The UUID is definitely there; removing the Cloudflare proxy triggered a different error in the Chatlio API:

`https://api.chatlio.com/v1/p/visitor/new?vsUuid=d5ac1fa5-fc43-72a2-277e-628a418b066c&ceUuid=27a8dbca-3d3c-48de-750b-13f908772485&currentPage=http%3A%2F%2Fchatlio.pragmatic-web.co.uk%2F`

`Failed to load resource: the server responded with a status of 400 (Bad Request)`

**Comment by dvdplm** [comment]
@jamesmorrison the widget UUID `27a8dbca-3d3c-48de-750b-13f908772485` does not exist in our DB so that explains the error message. Do you have another widget UUID to try with?

**Comment by ghost** [comment]
@dvdplm I don't have another; I think this was a "free" account used for dev testing. Could you send me another / reactivate my account?

My Chaltio account email is j [at] pragmatic-web [dot] co [dot] uk - when I sign in I'm asked to add a credit card to continue service.

Thanks

**Comment by dvdplm** [comment]
@jamesmorrison try now!

**Comment by ghost** [comment]
Thanks @dvdplm - working now. Will test / merge the PR.

**Comment by jeberly** [comment]
Thanks for fix guys!  I tested on non cloudflare WP install, and it works fine.  I merged https://github.com/PragmaticWebLimited/chatlio-for-wordpress/pull/5
